services:
    bitbag_sylius_acl_plugin.twig.extension.acl:
        class: BitBag\SyliusAclPlugin\Twig\AclExtension
        arguments:
            - "@bitbag_sylius_acl_plugin.resolver.admin_permission"
        tags:
            - { name: twig.extension }
