imports:
    - { resource: "@BitBagSyliusAclPlugin/Resources/config/services.yml" }
    - { resource: "@BitBagSyliusAclPlugin/Resources/config/resources.yml" }
    - { resource: "@BitBagSyliusAclPlugin/Resources/config/grids.yml" }
    - { resource: "@BitBagSyliusAclPlugin/Resources/config/permissions.yml" }
    - { resource: "@BitBagSyliusAclPlugin/Resources/config/twig_hooks.yml" }
